---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    project: {{ .Values.project }}
    app: {{ .Values.name }}
    env: {{ .Values.env }}
spec:
  selector:
    matchLabels:
      project: {{ .Values.project }}
      app: {{ .Values.name }}
      env: {{ .Values.env }}
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        project: {{ .Values.project }}
        app: {{ .Values.name }}
        env: {{ .Values.env }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.name }}
          env:
            - name: AUTHOR
              value: {{ .Values.envs.author }}
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          ports:
            - containerPort: {{ .Values.port }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 35
            periodSeconds: 60
            successThreshold: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 35
            periodSeconds: 60
            successThreshold: 1
          imagePullPolicy: Always
      restartPolicy: Always