---
apiVersion: v1
kind: Namespace
metadata:
  name: develop
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env
  namespace: develop
  labels:
    project: "task2"
data:
  .env: |+
    AUTHOR=Maksim
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service
  namespace: develop
  labels:
    project: "task2"
    app: service
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      project: "task2"
      app: service
      env: dev
  template:
    metadata:
      labels:
        project: "task2"
        app: service
        env: dev
    spec:
      containers:
      - name: service
        image: maximus123123/flask_app:v2
        env:
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
        ports:
          - containerPort: 8000
        livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 35
            periodSeconds: 60
            successThreshold:  1
        readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthcheck
              port: 8000
              scheme: HTTP
            initialDelaySeconds: 35
            periodSeconds: 60
            successThreshold:  1
        imagePullPolicy: Always
        volumeMounts:
          - name: env
            mountPath: "/app/.env"
            subPath: .env
            readOnly: true
      restartPolicy: Always
      volumes:
        - name: env
          configMap:
            name: env
---
kind: Service
apiVersion: v1
metadata:
  name: service
  namespace: develop
  labels:
    project: "task2"
spec:
  selector:
    app: service
    env: dev
  type: ClusterIP
  ports:
  - name: app
    port: 8000
    targetPort: 8000